spring:
  application:
    name: Consumer
  datasource:
    url: jdbc:h2:mem:${spring.application.name};DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      key-deserializer: "com.example.consumer.UuidDeserializer"
      properties:
        spring.json.type.mapping: cev:com.example.consumer.CustomerEvent
        interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
      client-id: ${spring.application.name}
      auto-offset-reset: earliest
      group-id: ${spring.application.name}
  sql:
    init:
      platform: h2

server:
  port: 9090

logging:
  level:
    org.springframework.kafka: debug
    org.springframework.boot: info
